package restassured.jira.schemas;

public class Schemas {

	static String getIssueSchema ="{\r\n"
			+ "  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\r\n"
			+ "  \"type\": \"object\",\r\n"
			+ "  \"properties\": {\r\n"
			+ "    \"expand\": {\r\n"
			+ "      \"type\": \"string\"\r\n"
			+ "    },\r\n"
			+ "    \"id\": {\r\n"
			+ "      \"type\": \"string\"\r\n"
			+ "    },\r\n"
			+ "    \"self\": {\r\n"
			+ "      \"type\": \"string\"\r\n"
			+ "    },\r\n"
			+ "    \"key\": {\r\n"
			+ "      \"type\": \"string\"\r\n"
			+ "    },\r\n"
			+ "    \"fields\": {\r\n"
			+ "      \"type\": \"object\",\r\n"
			+ "      \"properties\": {\r\n"
			+ "        \"statuscategorychangedate\": {\r\n"
			+ "          \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"issuetype\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"id\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"description\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"iconUrl\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"name\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"subtask\": {\r\n"
			+ "              \"type\": \"boolean\"\r\n"
			+ "            },\r\n"
			+ "            \"avatarId\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"entityId\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"hierarchyLevel\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"self\",\r\n"
			+ "            \"id\",\r\n"
			+ "            \"description\",\r\n"
			+ "            \"iconUrl\",\r\n"
			+ "            \"name\",\r\n"
			+ "            \"subtask\",\r\n"
			+ "            \"avatarId\",\r\n"
			+ "            \"entityId\",\r\n"
			+ "            \"hierarchyLevel\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"timespent\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"project\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"id\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"key\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"name\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"projectTypeKey\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"simplified\": {\r\n"
			+ "              \"type\": \"boolean\"\r\n"
			+ "            },\r\n"
			+ "            \"avatarUrls\": {\r\n"
			+ "              \"type\": \"object\",\r\n"
			+ "              \"properties\": {\r\n"
			+ "                \"48x48\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"24x24\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"16x16\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"32x32\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                }\r\n"
			+ "              },\r\n"
			+ "              \"required\": [\r\n"
			+ "                \"48x48\",\r\n"
			+ "                \"24x24\",\r\n"
			+ "                \"16x16\",\r\n"
			+ "                \"32x32\"\r\n"
			+ "              ]\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"self\",\r\n"
			+ "            \"id\",\r\n"
			+ "            \"key\",\r\n"
			+ "            \"name\",\r\n"
			+ "            \"projectTypeKey\",\r\n"
			+ "            \"simplified\",\r\n"
			+ "            \"avatarUrls\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"customfield_10032\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"fixVersions\": {\r\n"
			+ "          \"type\": \"array\",\r\n"
			+ "          \"items\": {}\r\n"
			+ "        },\r\n"
			+ "        \"aggregatetimespent\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"statusCategory\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"id\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"key\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"colorName\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"name\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"self\",\r\n"
			+ "            \"id\",\r\n"
			+ "            \"key\",\r\n"
			+ "            \"colorName\",\r\n"
			+ "            \"name\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"resolution\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"resolutiondate\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"workratio\": {\r\n"
			+ "          \"type\": \"integer\"\r\n"
			+ "        },\r\n"
			+ "        \"issuerestriction\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"issuerestrictions\": {\r\n"
			+ "              \"type\": \"object\"\r\n"
			+ "            },\r\n"
			+ "            \"shouldDisplay\": {\r\n"
			+ "              \"type\": \"boolean\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"issuerestrictions\",\r\n"
			+ "            \"shouldDisplay\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"watches\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"watchCount\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"isWatching\": {\r\n"
			+ "              \"type\": \"boolean\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"self\",\r\n"
			+ "            \"watchCount\",\r\n"
			+ "            \"isWatching\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"lastViewed\": {\r\n"
			+ "          \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"created\": {\r\n"
			+ "          \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"customfield_10020\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"customfield_10021\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"priority\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"iconUrl\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"name\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"id\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"self\",\r\n"
			+ "            \"iconUrl\",\r\n"
			+ "            \"name\",\r\n"
			+ "            \"id\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"labels\": {\r\n"
			+ "          \"type\": \"array\",\r\n"
			+ "          \"items\": {}\r\n"
			+ "        },\r\n"
			+ "        \"customfield_10016\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"customfield_10019\": {\r\n"
			+ "          \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"timeestimate\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"aggregatetimeoriginalestimate\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"versions\": {\r\n"
			+ "          \"type\": \"array\",\r\n"
			+ "          \"items\": {}\r\n"
			+ "        },\r\n"
			+ "        \"issuelinks\": {\r\n"
			+ "          \"type\": \"array\",\r\n"
			+ "          \"items\": {}\r\n"
			+ "        },\r\n"
			+ "        \"assignee\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"accountId\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"emailAddress\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"avatarUrls\": {\r\n"
			+ "              \"type\": \"object\",\r\n"
			+ "              \"properties\": {\r\n"
			+ "                \"48x48\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"24x24\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"16x16\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"32x32\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                }\r\n"
			+ "              },\r\n"
			+ "              \"required\": [\r\n"
			+ "                \"48x48\",\r\n"
			+ "                \"24x24\",\r\n"
			+ "                \"16x16\",\r\n"
			+ "                \"32x32\"\r\n"
			+ "              ]\r\n"
			+ "            },\r\n"
			+ "            \"displayName\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"active\": {\r\n"
			+ "              \"type\": \"boolean\"\r\n"
			+ "            },\r\n"
			+ "            \"timeZone\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"accountType\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"self\",\r\n"
			+ "            \"accountId\",\r\n"
			+ "            \"emailAddress\",\r\n"
			+ "            \"avatarUrls\",\r\n"
			+ "            \"displayName\",\r\n"
			+ "            \"active\",\r\n"
			+ "            \"timeZone\",\r\n"
			+ "            \"accountType\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"updated\": {\r\n"
			+ "          \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"status\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"description\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"iconUrl\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"name\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"id\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"statusCategory\": {\r\n"
			+ "              \"type\": \"object\",\r\n"
			+ "              \"properties\": {\r\n"
			+ "                \"self\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"id\": {\r\n"
			+ "                  \"type\": \"integer\"\r\n"
			+ "                },\r\n"
			+ "                \"key\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"colorName\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"name\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                }\r\n"
			+ "              },\r\n"
			+ "              \"required\": [\r\n"
			+ "                \"self\",\r\n"
			+ "                \"id\",\r\n"
			+ "                \"key\",\r\n"
			+ "                \"colorName\",\r\n"
			+ "                \"name\"\r\n"
			+ "              ]\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"self\",\r\n"
			+ "            \"description\",\r\n"
			+ "            \"iconUrl\",\r\n"
			+ "            \"name\",\r\n"
			+ "            \"id\",\r\n"
			+ "            \"statusCategory\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"components\": {\r\n"
			+ "          \"type\": \"array\",\r\n"
			+ "          \"items\": {}\r\n"
			+ "        },\r\n"
			+ "        \"timeoriginalestimate\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"description\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"type\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"version\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"content\": {\r\n"
			+ "              \"type\": \"array\",\r\n"
			+ "              \"items\": [\r\n"
			+ "                {\r\n"
			+ "                  \"type\": \"object\",\r\n"
			+ "                  \"properties\": {\r\n"
			+ "                    \"type\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"content\": {\r\n"
			+ "                      \"type\": \"array\",\r\n"
			+ "                      \"items\": [\r\n"
			+ "                        {\r\n"
			+ "                          \"type\": \"object\",\r\n"
			+ "                          \"properties\": {\r\n"
			+ "                            \"type\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"text\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            }\r\n"
			+ "                          },\r\n"
			+ "                          \"required\": [\r\n"
			+ "                            \"type\",\r\n"
			+ "                            \"text\"\r\n"
			+ "                          ]\r\n"
			+ "                        }\r\n"
			+ "                      ]\r\n"
			+ "                    }\r\n"
			+ "                  },\r\n"
			+ "                  \"required\": [\r\n"
			+ "                    \"type\",\r\n"
			+ "                    \"content\"\r\n"
			+ "                  ]\r\n"
			+ "                }\r\n"
			+ "              ]\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"type\",\r\n"
			+ "            \"version\",\r\n"
			+ "            \"content\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"timetracking\": {\r\n"
			+ "          \"type\": \"object\"\r\n"
			+ "        },\r\n"
			+ "        \"customfield_10015\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"security\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"attachment\": {\r\n"
			+ "          \"type\": \"array\",\r\n"
			+ "          \"items\": [\r\n"
			+ "            {\r\n"
			+ "              \"type\": \"object\",\r\n"
			+ "              \"properties\": {\r\n"
			+ "                \"self\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"id\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"filename\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"author\": {\r\n"
			+ "                  \"type\": \"object\",\r\n"
			+ "                  \"properties\": {\r\n"
			+ "                    \"self\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"accountId\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"emailAddress\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"avatarUrls\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"48x48\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"24x24\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"16x16\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"32x32\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"48x48\",\r\n"
			+ "                        \"24x24\",\r\n"
			+ "                        \"16x16\",\r\n"
			+ "                        \"32x32\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"displayName\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"active\": {\r\n"
			+ "                      \"type\": \"boolean\"\r\n"
			+ "                    },\r\n"
			+ "                    \"timeZone\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"accountType\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    }\r\n"
			+ "                  },\r\n"
			+ "                  \"required\": [\r\n"
			+ "                    \"self\",\r\n"
			+ "                    \"accountId\",\r\n"
			+ "                    \"emailAddress\",\r\n"
			+ "                    \"avatarUrls\",\r\n"
			+ "                    \"displayName\",\r\n"
			+ "                    \"active\",\r\n"
			+ "                    \"timeZone\",\r\n"
			+ "                    \"accountType\"\r\n"
			+ "                  ]\r\n"
			+ "                },\r\n"
			+ "                \"created\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"size\": {\r\n"
			+ "                  \"type\": \"integer\"\r\n"
			+ "                },\r\n"
			+ "                \"mimeType\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"content\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"thumbnail\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                }\r\n"
			+ "              },\r\n"
			+ "              \"required\": [\r\n"
			+ "                \"self\",\r\n"
			+ "                \"id\",\r\n"
			+ "                \"filename\",\r\n"
			+ "                \"author\",\r\n"
			+ "                \"created\",\r\n"
			+ "                \"size\",\r\n"
			+ "                \"mimeType\",\r\n"
			+ "                \"content\",\r\n"
			+ "                \"thumbnail\"\r\n"
			+ "              ]\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "              \"type\": \"object\",\r\n"
			+ "              \"properties\": {\r\n"
			+ "                \"self\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"id\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"filename\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"author\": {\r\n"
			+ "                  \"type\": \"object\",\r\n"
			+ "                  \"properties\": {\r\n"
			+ "                    \"self\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"accountId\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"emailAddress\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"avatarUrls\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"48x48\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"24x24\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"16x16\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"32x32\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"48x48\",\r\n"
			+ "                        \"24x24\",\r\n"
			+ "                        \"16x16\",\r\n"
			+ "                        \"32x32\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"displayName\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"active\": {\r\n"
			+ "                      \"type\": \"boolean\"\r\n"
			+ "                    },\r\n"
			+ "                    \"timeZone\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"accountType\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    }\r\n"
			+ "                  },\r\n"
			+ "                  \"required\": [\r\n"
			+ "                    \"self\",\r\n"
			+ "                    \"accountId\",\r\n"
			+ "                    \"emailAddress\",\r\n"
			+ "                    \"avatarUrls\",\r\n"
			+ "                    \"displayName\",\r\n"
			+ "                    \"active\",\r\n"
			+ "                    \"timeZone\",\r\n"
			+ "                    \"accountType\"\r\n"
			+ "                  ]\r\n"
			+ "                },\r\n"
			+ "                \"created\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"size\": {\r\n"
			+ "                  \"type\": \"integer\"\r\n"
			+ "                },\r\n"
			+ "                \"mimeType\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"content\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"thumbnail\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                }\r\n"
			+ "              },\r\n"
			+ "              \"required\": [\r\n"
			+ "                \"self\",\r\n"
			+ "                \"id\",\r\n"
			+ "                \"filename\",\r\n"
			+ "                \"author\",\r\n"
			+ "                \"created\",\r\n"
			+ "                \"size\",\r\n"
			+ "                \"mimeType\",\r\n"
			+ "                \"content\",\r\n"
			+ "                \"thumbnail\"\r\n"
			+ "              ]\r\n"
			+ "            }\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"aggregatetimeestimate\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"summary\": {\r\n"
			+ "          \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"creator\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"accountId\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"emailAddress\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"avatarUrls\": {\r\n"
			+ "              \"type\": \"object\",\r\n"
			+ "              \"properties\": {\r\n"
			+ "                \"48x48\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"24x24\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"16x16\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"32x32\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                }\r\n"
			+ "              },\r\n"
			+ "              \"required\": [\r\n"
			+ "                \"48x48\",\r\n"
			+ "                \"24x24\",\r\n"
			+ "                \"16x16\",\r\n"
			+ "                \"32x32\"\r\n"
			+ "              ]\r\n"
			+ "            },\r\n"
			+ "            \"displayName\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"active\": {\r\n"
			+ "              \"type\": \"boolean\"\r\n"
			+ "            },\r\n"
			+ "            \"timeZone\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"accountType\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"self\",\r\n"
			+ "            \"accountId\",\r\n"
			+ "            \"emailAddress\",\r\n"
			+ "            \"avatarUrls\",\r\n"
			+ "            \"displayName\",\r\n"
			+ "            \"active\",\r\n"
			+ "            \"timeZone\",\r\n"
			+ "            \"accountType\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"subtasks\": {\r\n"
			+ "          \"type\": \"array\",\r\n"
			+ "          \"items\": {}\r\n"
			+ "        },\r\n"
			+ "        \"reporter\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"accountId\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"emailAddress\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"avatarUrls\": {\r\n"
			+ "              \"type\": \"object\",\r\n"
			+ "              \"properties\": {\r\n"
			+ "                \"48x48\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"24x24\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"16x16\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                },\r\n"
			+ "                \"32x32\": {\r\n"
			+ "                  \"type\": \"string\"\r\n"
			+ "                }\r\n"
			+ "              },\r\n"
			+ "              \"required\": [\r\n"
			+ "                \"48x48\",\r\n"
			+ "                \"24x24\",\r\n"
			+ "                \"16x16\",\r\n"
			+ "                \"32x32\"\r\n"
			+ "              ]\r\n"
			+ "            },\r\n"
			+ "            \"displayName\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"active\": {\r\n"
			+ "              \"type\": \"boolean\"\r\n"
			+ "            },\r\n"
			+ "            \"timeZone\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"accountType\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"self\",\r\n"
			+ "            \"accountId\",\r\n"
			+ "            \"emailAddress\",\r\n"
			+ "            \"avatarUrls\",\r\n"
			+ "            \"displayName\",\r\n"
			+ "            \"active\",\r\n"
			+ "            \"timeZone\",\r\n"
			+ "            \"accountType\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"aggregateprogress\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"progress\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"total\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"progress\",\r\n"
			+ "            \"total\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"customfield_10001\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"environment\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"duedate\": {\r\n"
			+ "          \"type\": \"null\"\r\n"
			+ "        },\r\n"
			+ "        \"progress\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"progress\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"total\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"progress\",\r\n"
			+ "            \"total\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"votes\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"votes\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"hasVoted\": {\r\n"
			+ "              \"type\": \"boolean\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"self\",\r\n"
			+ "            \"votes\",\r\n"
			+ "            \"hasVoted\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"comment\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"comments\": {\r\n"
			+ "              \"type\": \"array\",\r\n"
			+ "              \"items\": [\r\n"
			+ "                {\r\n"
			+ "                  \"type\": \"object\",\r\n"
			+ "                  \"properties\": {\r\n"
			+ "                    \"self\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"id\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"author\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"self\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountId\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"emailAddress\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"avatarUrls\": {\r\n"
			+ "                          \"type\": \"object\",\r\n"
			+ "                          \"properties\": {\r\n"
			+ "                            \"48x48\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"24x24\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"16x16\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"32x32\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            }\r\n"
			+ "                          },\r\n"
			+ "                          \"required\": [\r\n"
			+ "                            \"48x48\",\r\n"
			+ "                            \"24x24\",\r\n"
			+ "                            \"16x16\",\r\n"
			+ "                            \"32x32\"\r\n"
			+ "                          ]\r\n"
			+ "                        },\r\n"
			+ "                        \"displayName\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"active\": {\r\n"
			+ "                          \"type\": \"boolean\"\r\n"
			+ "                        },\r\n"
			+ "                        \"timeZone\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountType\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"self\",\r\n"
			+ "                        \"accountId\",\r\n"
			+ "                        \"emailAddress\",\r\n"
			+ "                        \"avatarUrls\",\r\n"
			+ "                        \"displayName\",\r\n"
			+ "                        \"active\",\r\n"
			+ "                        \"timeZone\",\r\n"
			+ "                        \"accountType\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"body\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"type\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"version\": {\r\n"
			+ "                          \"type\": \"integer\"\r\n"
			+ "                        },\r\n"
			+ "                        \"content\": {\r\n"
			+ "                          \"type\": \"array\",\r\n"
			+ "                          \"items\": [\r\n"
			+ "                            {\r\n"
			+ "                              \"type\": \"object\",\r\n"
			+ "                              \"properties\": {\r\n"
			+ "                                \"type\": {\r\n"
			+ "                                  \"type\": \"string\"\r\n"
			+ "                                },\r\n"
			+ "                                \"content\": {\r\n"
			+ "                                  \"type\": \"array\",\r\n"
			+ "                                  \"items\": [\r\n"
			+ "                                    {\r\n"
			+ "                                      \"type\": \"object\",\r\n"
			+ "                                      \"properties\": {\r\n"
			+ "                                        \"type\": {\r\n"
			+ "                                          \"type\": \"string\"\r\n"
			+ "                                        },\r\n"
			+ "                                        \"text\": {\r\n"
			+ "                                          \"type\": \"string\"\r\n"
			+ "                                        }\r\n"
			+ "                                      },\r\n"
			+ "                                      \"required\": [\r\n"
			+ "                                        \"type\",\r\n"
			+ "                                        \"text\"\r\n"
			+ "                                      ]\r\n"
			+ "                                    }\r\n"
			+ "                                  ]\r\n"
			+ "                                }\r\n"
			+ "                              },\r\n"
			+ "                              \"required\": [\r\n"
			+ "                                \"type\",\r\n"
			+ "                                \"content\"\r\n"
			+ "                              ]\r\n"
			+ "                            }\r\n"
			+ "                          ]\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"type\",\r\n"
			+ "                        \"version\",\r\n"
			+ "                        \"content\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"updateAuthor\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"self\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountId\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"emailAddress\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"avatarUrls\": {\r\n"
			+ "                          \"type\": \"object\",\r\n"
			+ "                          \"properties\": {\r\n"
			+ "                            \"48x48\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"24x24\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"16x16\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"32x32\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            }\r\n"
			+ "                          },\r\n"
			+ "                          \"required\": [\r\n"
			+ "                            \"48x48\",\r\n"
			+ "                            \"24x24\",\r\n"
			+ "                            \"16x16\",\r\n"
			+ "                            \"32x32\"\r\n"
			+ "                          ]\r\n"
			+ "                        },\r\n"
			+ "                        \"displayName\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"active\": {\r\n"
			+ "                          \"type\": \"boolean\"\r\n"
			+ "                        },\r\n"
			+ "                        \"timeZone\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountType\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"self\",\r\n"
			+ "                        \"accountId\",\r\n"
			+ "                        \"emailAddress\",\r\n"
			+ "                        \"avatarUrls\",\r\n"
			+ "                        \"displayName\",\r\n"
			+ "                        \"active\",\r\n"
			+ "                        \"timeZone\",\r\n"
			+ "                        \"accountType\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"created\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"updated\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"jsdPublic\": {\r\n"
			+ "                      \"type\": \"boolean\"\r\n"
			+ "                    }\r\n"
			+ "                  },\r\n"
			+ "                  \"required\": [\r\n"
			+ "                    \"self\",\r\n"
			+ "                    \"id\",\r\n"
			+ "                    \"author\",\r\n"
			+ "                    \"body\",\r\n"
			+ "                    \"updateAuthor\",\r\n"
			+ "                    \"created\",\r\n"
			+ "                    \"updated\",\r\n"
			+ "                    \"jsdPublic\"\r\n"
			+ "                  ]\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                  \"type\": \"object\",\r\n"
			+ "                  \"properties\": {\r\n"
			+ "                    \"self\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"id\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"author\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"self\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountId\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"emailAddress\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"avatarUrls\": {\r\n"
			+ "                          \"type\": \"object\",\r\n"
			+ "                          \"properties\": {\r\n"
			+ "                            \"48x48\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"24x24\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"16x16\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"32x32\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            }\r\n"
			+ "                          },\r\n"
			+ "                          \"required\": [\r\n"
			+ "                            \"48x48\",\r\n"
			+ "                            \"24x24\",\r\n"
			+ "                            \"16x16\",\r\n"
			+ "                            \"32x32\"\r\n"
			+ "                          ]\r\n"
			+ "                        },\r\n"
			+ "                        \"displayName\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"active\": {\r\n"
			+ "                          \"type\": \"boolean\"\r\n"
			+ "                        },\r\n"
			+ "                        \"timeZone\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountType\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"self\",\r\n"
			+ "                        \"accountId\",\r\n"
			+ "                        \"emailAddress\",\r\n"
			+ "                        \"avatarUrls\",\r\n"
			+ "                        \"displayName\",\r\n"
			+ "                        \"active\",\r\n"
			+ "                        \"timeZone\",\r\n"
			+ "                        \"accountType\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"body\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"type\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"version\": {\r\n"
			+ "                          \"type\": \"integer\"\r\n"
			+ "                        },\r\n"
			+ "                        \"content\": {\r\n"
			+ "                          \"type\": \"array\",\r\n"
			+ "                          \"items\": [\r\n"
			+ "                            {\r\n"
			+ "                              \"type\": \"object\",\r\n"
			+ "                              \"properties\": {\r\n"
			+ "                                \"type\": {\r\n"
			+ "                                  \"type\": \"string\"\r\n"
			+ "                                },\r\n"
			+ "                                \"content\": {\r\n"
			+ "                                  \"type\": \"array\",\r\n"
			+ "                                  \"items\": [\r\n"
			+ "                                    {\r\n"
			+ "                                      \"type\": \"object\",\r\n"
			+ "                                      \"properties\": {\r\n"
			+ "                                        \"type\": {\r\n"
			+ "                                          \"type\": \"string\"\r\n"
			+ "                                        },\r\n"
			+ "                                        \"text\": {\r\n"
			+ "                                          \"type\": \"string\"\r\n"
			+ "                                        }\r\n"
			+ "                                      },\r\n"
			+ "                                      \"required\": [\r\n"
			+ "                                        \"type\",\r\n"
			+ "                                        \"text\"\r\n"
			+ "                                      ]\r\n"
			+ "                                    }\r\n"
			+ "                                  ]\r\n"
			+ "                                }\r\n"
			+ "                              },\r\n"
			+ "                              \"required\": [\r\n"
			+ "                                \"type\",\r\n"
			+ "                                \"content\"\r\n"
			+ "                              ]\r\n"
			+ "                            }\r\n"
			+ "                          ]\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"type\",\r\n"
			+ "                        \"version\",\r\n"
			+ "                        \"content\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"updateAuthor\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"self\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountId\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"emailAddress\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"avatarUrls\": {\r\n"
			+ "                          \"type\": \"object\",\r\n"
			+ "                          \"properties\": {\r\n"
			+ "                            \"48x48\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"24x24\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"16x16\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"32x32\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            }\r\n"
			+ "                          },\r\n"
			+ "                          \"required\": [\r\n"
			+ "                            \"48x48\",\r\n"
			+ "                            \"24x24\",\r\n"
			+ "                            \"16x16\",\r\n"
			+ "                            \"32x32\"\r\n"
			+ "                          ]\r\n"
			+ "                        },\r\n"
			+ "                        \"displayName\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"active\": {\r\n"
			+ "                          \"type\": \"boolean\"\r\n"
			+ "                        },\r\n"
			+ "                        \"timeZone\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountType\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"self\",\r\n"
			+ "                        \"accountId\",\r\n"
			+ "                        \"emailAddress\",\r\n"
			+ "                        \"avatarUrls\",\r\n"
			+ "                        \"displayName\",\r\n"
			+ "                        \"active\",\r\n"
			+ "                        \"timeZone\",\r\n"
			+ "                        \"accountType\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"created\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"updated\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"jsdPublic\": {\r\n"
			+ "                      \"type\": \"boolean\"\r\n"
			+ "                    }\r\n"
			+ "                  },\r\n"
			+ "                  \"required\": [\r\n"
			+ "                    \"self\",\r\n"
			+ "                    \"id\",\r\n"
			+ "                    \"author\",\r\n"
			+ "                    \"body\",\r\n"
			+ "                    \"updateAuthor\",\r\n"
			+ "                    \"created\",\r\n"
			+ "                    \"updated\",\r\n"
			+ "                    \"jsdPublic\"\r\n"
			+ "                  ]\r\n"
			+ "                },\r\n"
			+ "                {\r\n"
			+ "                  \"type\": \"object\",\r\n"
			+ "                  \"properties\": {\r\n"
			+ "                    \"self\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"id\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"author\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"self\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountId\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"emailAddress\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"avatarUrls\": {\r\n"
			+ "                          \"type\": \"object\",\r\n"
			+ "                          \"properties\": {\r\n"
			+ "                            \"48x48\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"24x24\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"16x16\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"32x32\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            }\r\n"
			+ "                          },\r\n"
			+ "                          \"required\": [\r\n"
			+ "                            \"48x48\",\r\n"
			+ "                            \"24x24\",\r\n"
			+ "                            \"16x16\",\r\n"
			+ "                            \"32x32\"\r\n"
			+ "                          ]\r\n"
			+ "                        },\r\n"
			+ "                        \"displayName\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"active\": {\r\n"
			+ "                          \"type\": \"boolean\"\r\n"
			+ "                        },\r\n"
			+ "                        \"timeZone\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountType\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"self\",\r\n"
			+ "                        \"accountId\",\r\n"
			+ "                        \"emailAddress\",\r\n"
			+ "                        \"avatarUrls\",\r\n"
			+ "                        \"displayName\",\r\n"
			+ "                        \"active\",\r\n"
			+ "                        \"timeZone\",\r\n"
			+ "                        \"accountType\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"body\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"type\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"version\": {\r\n"
			+ "                          \"type\": \"integer\"\r\n"
			+ "                        },\r\n"
			+ "                        \"content\": {\r\n"
			+ "                          \"type\": \"array\",\r\n"
			+ "                          \"items\": [\r\n"
			+ "                            {\r\n"
			+ "                              \"type\": \"object\",\r\n"
			+ "                              \"properties\": {\r\n"
			+ "                                \"type\": {\r\n"
			+ "                                  \"type\": \"string\"\r\n"
			+ "                                },\r\n"
			+ "                                \"content\": {\r\n"
			+ "                                  \"type\": \"array\",\r\n"
			+ "                                  \"items\": [\r\n"
			+ "                                    {\r\n"
			+ "                                      \"type\": \"object\",\r\n"
			+ "                                      \"properties\": {\r\n"
			+ "                                        \"type\": {\r\n"
			+ "                                          \"type\": \"string\"\r\n"
			+ "                                        },\r\n"
			+ "                                        \"text\": {\r\n"
			+ "                                          \"type\": \"string\"\r\n"
			+ "                                        }\r\n"
			+ "                                      },\r\n"
			+ "                                      \"required\": [\r\n"
			+ "                                        \"type\",\r\n"
			+ "                                        \"text\"\r\n"
			+ "                                      ]\r\n"
			+ "                                    }\r\n"
			+ "                                  ]\r\n"
			+ "                                }\r\n"
			+ "                              },\r\n"
			+ "                              \"required\": [\r\n"
			+ "                                \"type\",\r\n"
			+ "                                \"content\"\r\n"
			+ "                              ]\r\n"
			+ "                            }\r\n"
			+ "                          ]\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"type\",\r\n"
			+ "                        \"version\",\r\n"
			+ "                        \"content\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"updateAuthor\": {\r\n"
			+ "                      \"type\": \"object\",\r\n"
			+ "                      \"properties\": {\r\n"
			+ "                        \"self\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountId\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"emailAddress\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"avatarUrls\": {\r\n"
			+ "                          \"type\": \"object\",\r\n"
			+ "                          \"properties\": {\r\n"
			+ "                            \"48x48\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"24x24\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"16x16\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            },\r\n"
			+ "                            \"32x32\": {\r\n"
			+ "                              \"type\": \"string\"\r\n"
			+ "                            }\r\n"
			+ "                          },\r\n"
			+ "                          \"required\": [\r\n"
			+ "                            \"48x48\",\r\n"
			+ "                            \"24x24\",\r\n"
			+ "                            \"16x16\",\r\n"
			+ "                            \"32x32\"\r\n"
			+ "                          ]\r\n"
			+ "                        },\r\n"
			+ "                        \"displayName\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"active\": {\r\n"
			+ "                          \"type\": \"boolean\"\r\n"
			+ "                        },\r\n"
			+ "                        \"timeZone\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"accountType\": {\r\n"
			+ "                          \"type\": \"string\"\r\n"
			+ "                        }\r\n"
			+ "                      },\r\n"
			+ "                      \"required\": [\r\n"
			+ "                        \"self\",\r\n"
			+ "                        \"accountId\",\r\n"
			+ "                        \"emailAddress\",\r\n"
			+ "                        \"avatarUrls\",\r\n"
			+ "                        \"displayName\",\r\n"
			+ "                        \"active\",\r\n"
			+ "                        \"timeZone\",\r\n"
			+ "                        \"accountType\"\r\n"
			+ "                      ]\r\n"
			+ "                    },\r\n"
			+ "                    \"created\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"updated\": {\r\n"
			+ "                      \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"jsdPublic\": {\r\n"
			+ "                      \"type\": \"boolean\"\r\n"
			+ "                    }\r\n"
			+ "                  },\r\n"
			+ "                  \"required\": [\r\n"
			+ "                    \"self\",\r\n"
			+ "                    \"id\",\r\n"
			+ "                    \"author\",\r\n"
			+ "                    \"body\",\r\n"
			+ "                    \"updateAuthor\",\r\n"
			+ "                    \"created\",\r\n"
			+ "                    \"updated\",\r\n"
			+ "                    \"jsdPublic\"\r\n"
			+ "                  ]\r\n"
			+ "                }\r\n"
			+ "              ]\r\n"
			+ "            },\r\n"
			+ "            \"self\": {\r\n"
			+ "              \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"maxResults\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"total\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"startAt\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"comments\",\r\n"
			+ "            \"self\",\r\n"
			+ "            \"maxResults\",\r\n"
			+ "            \"total\",\r\n"
			+ "            \"startAt\"\r\n"
			+ "          ]\r\n"
			+ "        },\r\n"
			+ "        \"worklog\": {\r\n"
			+ "          \"type\": \"object\",\r\n"
			+ "          \"properties\": {\r\n"
			+ "            \"startAt\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"maxResults\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"total\": {\r\n"
			+ "              \"type\": \"integer\"\r\n"
			+ "            },\r\n"
			+ "            \"worklogs\": {\r\n"
			+ "              \"type\": \"array\",\r\n"
			+ "              \"items\": {}\r\n"
			+ "            }\r\n"
			+ "          },\r\n"
			+ "          \"required\": [\r\n"
			+ "            \"startAt\",\r\n"
			+ "            \"maxResults\",\r\n"
			+ "            \"total\",\r\n"
			+ "            \"worklogs\"\r\n"
			+ "          ]\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"required\": [\r\n"
			+ "        \"statuscategorychangedate\",\r\n"
			+ "        \"issuetype\",\r\n"
			+ "        \"timespent\",\r\n"
			+ "        \"project\",\r\n"
			+ "        \"customfield_10032\",\r\n"
			+ "        \"fixVersions\",\r\n"
			+ "        \"aggregatetimespent\",\r\n"
			+ "        \"statusCategory\",\r\n"
			+ "        \"resolution\",\r\n"
			+ "        \"resolutiondate\",\r\n"
			+ "        \"workratio\",\r\n"
			+ "        \"issuerestriction\",\r\n"
			+ "        \"watches\",\r\n"
			+ "        \"lastViewed\",\r\n"
			+ "        \"created\",\r\n"
			+ "        \"customfield_10020\",\r\n"
			+ "        \"customfield_10021\",\r\n"
			+ "        \"priority\",\r\n"
			+ "        \"labels\",\r\n"
			+ "        \"customfield_10016\",\r\n"
			+ "        \"customfield_10019\",\r\n"
			+ "        \"timeestimate\",\r\n"
			+ "        \"aggregatetimeoriginalestimate\",\r\n"
			+ "        \"versions\",\r\n"
			+ "        \"issuelinks\",\r\n"
			+ "        \"assignee\",\r\n"
			+ "        \"updated\",\r\n"
			+ "        \"status\",\r\n"
			+ "        \"components\",\r\n"
			+ "        \"timeoriginalestimate\",\r\n"
			+ "        \"description\",\r\n"
			+ "        \"timetracking\",\r\n"
			+ "        \"customfield_10015\",\r\n"
			+ "        \"security\",\r\n"
			+ "        \"attachment\",\r\n"
			+ "        \"aggregatetimeestimate\",\r\n"
			+ "        \"summary\",\r\n"
			+ "        \"creator\",\r\n"
			+ "        \"subtasks\",\r\n"
			+ "        \"reporter\",\r\n"
			+ "        \"aggregateprogress\",\r\n"
			+ "        \"customfield_10001\",\r\n"
			+ "        \"environment\",\r\n"
			+ "        \"duedate\",\r\n"
			+ "        \"progress\",\r\n"
			+ "        \"votes\",\r\n"
			+ "        \"comment\",\r\n"
			+ "        \"worklog\"\r\n"
			+ "      ]\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"required\": [\r\n"
			+ "    \"expand\",\r\n"
			+ "    \"id\",\r\n"
			+ "    \"self\",\r\n"
			+ "    \"key\",\r\n"
			+ "    \"fields\"\r\n"
			+ "  ]\r\n"
			+ "}";
}
